# api-gateway/src/main/resources/application.yml
server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://service-authentification
          predicates:
            - Path=/auth/**
        - id: assurance-service
          uri: lb://service-assurance
          predicates:
            - Path=/clients/**
        - id: sinistre-service
          uri: lb://service-sinistre
          predicates:
            - Path=/sinistres/**
        - id: admin-service
          uri: lb://service-admin
          predicates:
            - Path=/admin/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always