server:
  port: 8761

spring:
  application:
    name: discovery-service
  cloud:
    config:
      enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false  # Pour dev, désactive la protection
    eviction-interval-timer-in-ms: 15000